[package]
name = "policy"
version = "0.2.0"
edition = "2021"

[lib]
name = "policy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
rand = "0.9.2"
rayon = "1.8.0"