# @package _global_

env:
  name: "cwcvrp"
  num_loc: 100
  area: "riomaior"
  waste_type: "plastic"
  distance_method: "gmaps"
  vertex_method: "mmn"
  edge_threshold: 1.0
  edge_method: "knn"

  # Rewards / Costs
  cost_weight: 10.0      # w_len
  overflow_penalty: 10.0 # w_over
  collection_reward: 10.0 # w_waste
