# Evaluation Configuration
decode_type: "greedy"
decode_strategy: "greedy"
softmax_temperature: 1.0
val_size: 12800
offset: 0
eval_batch_size: 256
max_calc_batch_size: 12800
results_dir: "results_eval"
model_path: "checkpoints/best_model.pt"

# Problem Definition
problem: "cwcvrp"


# Graph
focus_graph: ""
focus_size: 0

# Flags
overwrite_flag: ""
no_cuda_flag: ""
no_progress_bar_flag: ""
compress_mask_flag: ""
multiprocessing_flag: ""
output_file: ""
