# General
verbose: true
seed: 42
start: 0
epochs: 7
problem: "wcvrp"

# HPO Specifics
eta: 5
n_pop: 20
fevals: 25
metric: "both"
hpo_method: "dehbo"
range: [0.0, 2.0]
max_tres: 40
h_epochs: 3
mutpb: 0.3
cxpb: 0.5

# Environment Overrides for HPO
size: 20
area: "riomaior"
wtype: "plastic"
edge_t: 0.3
edge_m: "knn"
vertex_m: "mmn"

# Optimization Overrides
optim: "rmsprop"
lr_model: 0.0001
lr_cv: 0.0001
lr_scheduler: "lambda"
lr_decay: 1.0
b_size: 256

# RL Baseline
bl: "exponential"
max_norm: 1.0
exp_beta: 0.8
bl_alpha: 0.05
acc_steps: 1

# Model Selection
model_names: ["am"]
model_encoders: ["gat"]
horizon: [0, 0, 0, 0, 3]
wb_mode: "disabled"
