# General
verbose: true
n_cores: 22

# Simulation Settings
seed: 42
n_days: 31
size: 100
n_samples: 10
checkpoints: 30
real_time_log: 1

# Policy Parameters
policies: ["tsp"]
n_vehicles: 0
problem: "cwcvrp"
gate_prob_threshold: 0.1
mask_prob_threshold: 0.1
