# General
verbose: true
n_cores: 22

# Simulation Settings
seed: 42
n_days: 31
n_bins: 100
n_samples: 10
checkpoints: 30
real_time_log: 1
problem: "cwcvrp"

# Policy Parameters
policies: ["hgs"]
vehicles: 0
gate_prob_threshold: "0.1"
mask_prob_threshold: "0.1"
