# @package _global_

# General
verbose: true
seed: 42
start: 0

# Data Configuration
data:
  n_epochs: 100
  problem: "vrpp"
  dataset_size: 1280
  val_size: 1280
  test_size: 31
  data_distributions: ["gamma1"]
  num_locs: [20, 50, 100, 170]
  dataset_type: "train_time"
  filename: "time"
  focus_size: 31
  data_dir: "daily_waste"
