# @package _global_

# General
verbose: true
seed: 42
start: 0

# Data Configuration
data:
  n_epochs: 100
  problem: "vrpp"
  dataset_size: 1280
  data_distributions: ["gamma1"]
  num_locs: [20, 50, 100, 170]
  dataset_type: "train_time"
  filename: "time"
  focus_size: 1280
  data_dir: "datasets"

# Training specific overrides often found in old gen_data
train:
  val_data_size: 128
