# @package _global_

# General
verbose: true
seed: 42
cpu_cores: 0

# Simulation Configuration (matches SimConfig)
sim:
  days: 31
  size: 170
  n_samples: 10
  checkpoint_days: 0
  real_time_log: false
  policies: ["alns", "bcp", "cvrp", "hgs", "lkh", "sans", "tsp", "vrpp"] # ['alns', 'bcp', 'cvrp', 'hgs', 'lkh', 'sans', 'tsp', 'vrpp']
  n_vehicles: 1
  problem: "cwcvrp"
  gate_prob_threshold: 0.1
  mask_prob_threshold: 0.1
  area: "riomaior"
  waste_type: "plastic"
  output_dir: "output"
  checkpoint_dir: "checkpoints"
