hgs_alns:
  custom:
    - time_limit: 60
    - population_size: 50
    - elite_size: 10
    - mutation_rate: 0.2
    - alns_education_iterations: 50
    - engine: "hgs_alns"
    - must_go: ["mg_lookahead_days7.xml"]
    - post_processing: []
