# @package _global_

env:
  name: "sdwcvrp"
  num_loc: 50
  area: "riomaior"
  waste_type: "plastic"

  # Stochastic parameters
  stochastic: true
  variance: 0.1

  # Generation parameters
  distance_method: "gmaps"
  vertex_method: "mmn"
  edge_threshold: 1.0
  edge_method: "knn"

  # Reward/Cost Weights
  cost_weight: 1.0
  overflow_penalty: 10.0
  collection_reward: 10.0
